### ISSUE TITLE
Why are the database dates unique?

### ISSUE THREAD

**Issue by TheBestMoshe** [KATT/zart#12]
Is there any specific reason why the `createdAt` and `updatedAt` fields are unique? I would think it should not be unique as it can cause random errors for simultaneous creations. Any `prismsa.post.createMany` will fail with a unique constraints error.

https://github.com/KATT/zart/blob/main/prisma/schema.prisma#L20-L21

```
  createdAt DateTime @unique @default(now())
  updatedAt DateTime @unique @default(now())
```

**Comment by KATT** [comment]
Yeah, they shouldn't. Think I had them unique so they could be used as a cursor in pagination. Feel free to submit a PR to change this!
