### ISSUE TITLE
Issue with 'expo-yarn-workspaces' on windows

### ISSUE THREAD

**Issue by JakeSchroeder** [KATT/zart#13]
Hey there,

I tried installing on windows and got this:

error C:\Users\Master\Documents\Development\ZART-test\node_modules\@expo-next-monorepo-example\expo: Command failed.
Exit code: 1
Command: expo-yarn-workspaces postinstall && cd ../..
Arguments:
Directory: C:\Users\Master\Documents\Development\ZART-test\node_modules\@expo-next-monorepo-example\expo
Output:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Master\Documents\Development\ZART-test\node_modules\node_modules\expo-yarn-workspaces\bin\expo-yarn-workspaces.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Seems to pertain to this:
https://github.com/expo/expo/issues/6983

-------------------------------------------------------------
The fix for me was updating expo-yarn-workspaces from ^1.5.1 to version ^1.7.0

Cheers!

**Comment by KATT** [comment]
Thanks for sharing the solution, do you wanna make a PR? ☺

**Comment by JakeSchroeder** [comment]
Sure thing ill do that now!
