### ISSUE TITLE
Confusing Imports

### ISSUE THREAD

**Issue by sean-brydon** [KATT/zart#19]
Been having a flick around this repo and I really like this as a starter :) 

A few things suggestions

<img width="197" alt="CleanShot 2022-02-02 at 20 07 55@2x" src="https://user-images.githubusercontent.com/55134778/152229216-3d02aa11-d477-4bd3-8a21-871ab6b8a44f.png">

`trpc.tsx` doesn't need to be in both of the `react` and `react-native` packages - could be moved to a `shared` package which would also be a good place to add the shared components/hooks throughout the expo and nextjs app 

The `react-native` packages imports the `react` trpc client which confused me a little 

---
Really well done on this tho :) Will be using this for my next RN project ... Happy to create a PR for the changes I mentioned above if you agree with what I'm saying

**Comment by KATT** [comment]
I've not done too many RN projects and I did the vast majority of this template in a day, so it's probably lacking some stuff. Super happy to receive PRs, will add you as a contributor so you can push a branch up without forking

**Comment by KATT** [comment]
It is intended that the react-native package should import react client.

That's shared "react" utils that'd work both for web and RN.
Could be named more clearly.

Feel free to do tweaks
