### ISSUE TITLE
Remake with turbo

### ISSUE THREAD

**Issue by juliusmarminge** [KATT/zart#21]
Hi,

I have been trying to use this stack but can't get it to work. Don't want to be bound to yarn as hard as this project is setup, hence I wanted to try building it with turbo.

Here is my repo: https://github.com/juliusmarminge/turbo-expo-next-starter

I have come as far as getting the expo app working, and tRPC working on the Next app. However, I struggle to get tRPC working on the expo app.

Have you tried making this work with another set of toolings? For me it feels like magic how the dependencies comes together when the packages have no dependencies, and all expo packages have to be symlinked in `apps/expo/package.json`.

**Comment by KATT** [comment]
There is an example working here https://trpc.io/docs/awesome-trpc but not with Expo I think
