### ISSUE TITLE
This looks cool - I'm looking at something similar...

### ISSUE THREAD

**Issue by mwarger** [KATT/zart#7]
@KATT 

What amazing timing... I just started doing something similar: https://github.com/mwarger/nextpo-trpc

I went the route of combining everything as one project instead of using the mono-repo starter.  I based it on a template I figured out as well from here: https://github.com/mwarger/expo-nextjs-dripsy-moti-setup

As you work on TRPC, I would love if you could take a look at the basic stubs that are there, especially if you think something like React-Admin would be useful for TRPC...  In this project, I created a basic DataProvider implementation that's compatible with react-admin - if it's something that I end up liking I will split it out for the community.  Still much work to be done with that aspect.  

Sorry for the issue spam, as well - if this isn't the right place for this type of question, let me know.  I just wasn't sure where to put it.  If this isn't the right place, feel free to DM me on twitter @mwarger

Thanks!

**Comment by KATT** [comment]
Thanks for reaching out! I've [added you as a contributor](https://github.com/KATT/zart/invitations) on this repo in case you want us to just put our heads together on one repo instead of 2.


> What amazing timing... I just started doing something similar: https://github.com/mwarger/nextpo-trpc
> 
> I went the route of combining everything as one project instead of using the mono-repo starter. I based it on a template I figured out as well from here: https://github.com/mwarger/expo-nextjs-dripsy-moti-setup

Cool! Didn't know you could do that, not dug enough to see if I prefer it or not.


> As you work on TRPC, I would love if you could take a look at the basic stubs that are there, especially if you think something like React-Admin would be useful for TRPC... In this project, I created a basic DataProvider implementation that's compatible with react-admin - if it's something that I end up liking I will split it out for the community. Still much work to be done with that aspect.

Seems pretty cool to plug in React Admin - I think you _should_ be able to autogen react admin based on the router [similar to this idea with Retool](https://github.com/trpc/trpc/issues/703)? 

> Sorry for the issue spam, as well - if this isn't the right place for this type of question, let me know. I just wasn't sure where to put it. If this isn't the right place, feel free to DM me on twitter @mwarger

This is the perfect place!

> Thanks!

Thank **you**!

**Comment by mwarger** [comment]
I actually found that issue re Retool and started looking into that as well.  Haven't looked into it enough yet to see how that would work.  Thanks for the invite.  I have done the same for the other repo.

**Comment by KATT** [comment]
Closing this - feel free to open another issue or DM me on twitter :)
