### ISSUE TITLE
Separate router/impl

### ISSUE THREAD

**Issue by vjpr** [KATT/zart#8]
`@zart/api` is not defined as a dep in https://github.com/KATT/zart/blob/60e7b37445/apps/nextjs/package.json

Related to https://github.com/trpc/trpc/discussions/1003, perhaps the `export type AppRouter` and `createContext` should be in its own package called `@zart/router` which depends on `@zart/api`.

This would pave the way to remove `@zart/nextjs`'s dependency on `@zart/api` in the future. Say you want to expose your `@zart/router` publicly, you don't want the consumer to have access to the client, and also if the router's schema has not changed, you don't need to rebuild the client.

**Comment by KATT** [comment]
Let's keep the discussion in https://github.com/trpc/trpc/discussions/1003

**Comment by KATT** [comment]
I was a bit early to lock the discussion - feel free to add some comments if you think it's distinctly separate discussions :)

**Comment by KATT** [comment]
(or close it)
